version: '3.8'

name: doublestack-shop

services:
  doublestack-shop:
    image: lastthree/doublestack-shop:{version} # 请将 {version} 替换为实际版本号，如 v2.0.9
    container_name: doublestack-shop
    ports:
      - "8000:8001"
    volumes:
      - ./backend/data:/app/data
      - ./backend/repos:/app/repos
      - ./backend/scripts:/app/scripts
      - ./backend/backup:/app/backup
      - ./backend/logs:/app/logs
      - ./backend/image:/app/image
      - /var/run/docker.sock:/var/run/docker.sock
      - /:/host:rw
      - /etc/docker:/etc/docker:rw
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    environment:
      - PYTHONUNBUFFERED=1
    privileged: true
    restart: unless-stopped
